### ISSUE TITLE
Mobile responsive header format

### ISSUE THREAD

**Issue by roberthbarnes** [magicboxtechnology/magicboxtechnology.github.io#6]
When I use my iPhone with the website in mobile responsive format the header defaults to half the screen. Can we resize this and change the width?

**Comment by iancrowther** [comment]
<img width="320" alt="screen shot 2015-10-09 at 15 25 27" src="https://cloud.githubusercontent.com/assets/76060/10396358/0360652e-6e9a-11e5-8c7d-67a95a0b4dd2.png">
